packages:
  - .

minimumReleaseAge: 0

allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  protobufjs: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@google/genai'
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - protobufjs
  - sharp
  - unrs-resolver
