import type { QuestionCategory } from '@/configs/questions'
import type { Dictionary } from '@/types/i18n'

/**
 * English dictionary
 *
 * `satisfies Dictionary` 保證與繁中字典的鍵完全一致,缺漏會編譯錯誤。
 * 命盤上的干支、十神為專有名詞,保留漢字呈現。
 */
export const en = {
  common: {
    siteName: 'BaziAsk',
    login: 'Sign in',
    logout: 'Sign out',
    history: 'My readings',
    backHome: 'Back to home',
    loading: 'Loading…',
  },
  home: {
    tagline: 'When life feels uncertain, let Bazi offer you a direction',
    footerLine1: 'Chart computed precisely by algorithm · Interpretation generated by AI',
    footerLine2:
      'Guest data is never stored · Member readings are private and deletable anytime',
    askAgain: 'Ask again',
    bannerText:
      'Sign in to save every reading, revisit anytime, and get a higher daily quota.',
    bannerCta: 'Sign up free',
    errNetwork: 'Connection lost. Please try again later.',
    errUnknown: 'Something went wrong. Please try again later.',
  },
  steps: ['Your question', 'Birth details', 'Reading'] as [string, string, string],
  question: {
    title: 'What weighs on your mind right now?',
    desc: 'Pick a topic, then write down what troubles you — the reading will fit your situation better.',
    next: 'Next: birth details',
    categories: {
      綜合運勢: 'General',
      事業工作: 'Career',
      感情婚姻: 'Love',
      財運: 'Wealth',
      學業考試: 'Studies',
    } satisfies Record<QuestionCategory, string>,
    placeholders: {
      綜合運勢: 'Things have been up and down lately. What should I watch for…',
      事業工作: 'I feel stuck at work. Should I change my path…',
      感情婚姻: 'Our relationship hit a plateau. Are we right for each other…',
      財運: 'I want to invest or start a business. Is my wealth luck ready…',
      學業考試: 'Exam pressure is heavy. How should I pace myself…',
    } satisfies Record<QuestionCategory, string>,
  },
  birth: {
    title: 'Your birth time',
    desc: 'Use the solar (Gregorian) calendar. The hour affects the Hour Pillar — be as precise as you can; minutes can be 00 if unsure.',
    dateLabel: 'Date of birth (solar)',
    timeLabel: 'Time of birth',
    genderLabel: 'Sex (for luck pillars)',
    female: 'Female',
    male: 'Male',
    back: 'Back',
    submit: 'Get my reading',
    submitting: 'Computing…',
    errNoDate: 'Please choose your date of birth.',
  },
  chart: {
    title: 'Your chart',
    zodiacPrefix: 'Zodiac ',
    hiddenPrefix: 'Hidden ',
    dayMaster: 'Day Master',
    wuxingTitle: 'Five Elements',
    wuxingAll: 'All five present',
    lackPrefix: 'lacks ',
    daYun: 'Luck Pillars',
    agePrefix: 'age ',
    ageSuffix: '',
    startYearSuffix: ' onwards',
  },
  interpretation: {
    title: 'Reading',
    copy: 'Copy',
    copied: 'Copied ✓',
    generating: 'Reading your chart…',
    disclaimer:
      'This content is generated by AI based on traditional Bazi astrology, for reference and entertainment only — not medical, legal, or investment advice.',
  },
  auth: {
    signinTitle: 'Sign in',
    signupTitle: 'Create account',
    email: 'Email',
    password: 'Password (min. 6 characters)',
    signin: 'Sign in',
    signup: 'Create account',
    processing: 'Processing…',
    noAccount: 'No account yet?',
    hasAccount: 'Already have an account?',
    toSignup: 'Sign up',
    toSignin: 'Sign in',
    hint: 'Readings are saved automatically after sign-in — revisit or delete anytime',
    errSignin: 'Sign-in failed: incorrect email or password.',
    errInvalid: 'Please enter a valid email and a password of at least 6 characters.',
    errRegistered: 'This email is already registered. Please sign in.',
    errSignup: 'Sign-up failed. Check the email format and password length (min. 6).',
    confirmSent:
      'Confirmation email sent. Click the link in your inbox, then come back to sign in.',
    close: 'Close',
  },
  historyPage: {
    title: 'My readings',
    askAgain: '← Ask again',
    empty: 'No readings yet — go ask your first question.',
    needLogin: 'Sign in to view your readings.',
    notConfigured: 'Member system (Supabase) not configured. See README.',
    expand: 'Expand ▼',
    collapse: 'Collapse ▲',
    remove: 'Delete this reading',
  },
} satisfies Dictionary
